services:
  - type: web
    name: albatross-pro
    runtime: python
    buildCommand: |
      git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      git submodule update --init --recursive
      pip install -r requirements.txt
    startCommand: "gunicorn -c gunicorn.conf.py albatross_pro.web.app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: AUTH_DB_URI
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
