services:
  - type: web
    name: albatross-pro
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=. gunicorn albatross_pro.web.app:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: AUTH_DB_URI
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
